# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT1: ${{ secrets.METRICS_TOKEN }}
          GITHUB_CONTEXT2: ${{ secrets.REPO_METRICS_TOKEN }}
          GITHUB_CONTEXT3: ${{ env.PUB_METRICS_TOKEN }}
        run: echo "GITHUB_CONTEXT1 = $GITHUB_CONTEXT   GITHUB_CONTEXT2 = $GITHUB_CONTEXT2   GITHUB_CONTEXT3 = $GITHUB_CONTEXT3"
        
      
